apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotation-deploy
  namespace: vkpaints-dev-ns
spec:
  selector:
    matchLabels:
      app: quotation-service
  template:
    metadata:
      labels:
        app: quotation-service
    spec:
      containers:
      - name: quotation-container
        image: shubha20/vk-paints_product-service:v1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: quotation-config
        # - secretRef:
        #     name: product-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 10

        - containerPort: 3000
